# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to Discord

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 16 * * *'

jobs:
  publish:

    runs-on: ubuntu-latest
    environment:
      name: production

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm start
      env:
        WEB_HOOK_URL: ${{ secrets.WEB_HOOK_URL }}

